spring:
  profiles:
    active: mysql
  batch.job.names: ${job.name:NONE}

logging.level.org.springframework.batch: DEBUG

---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: rivernine
      driver-class-name: org.h2.Driver
---
spring:
  profiles: mysql
  source-datasource:
    hikari:
      # MYSQL_ADDR:PORT/DATABASE
      jdbc-url: jdbc:mysql://192.168.56.103:3306/etl
      username: rivernine
      password: rivernine
      # mysql용 jdbc드라이버
      driver-class-name: com.mysql.jdbc.Driver
  target-datasource:
    hikari:
      jdbc-url: jdbc:mysql://192.168.56.103:3307/etl
      username: rivernine
      password: rivernine      
      driver-class-name: com.mysql.jdbc.Driver
