version: '3'
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    ports:
      - 9090:9090
  
  grafana:
    container_name: grafana
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 9091:3000
    volumes:
      - ./defaults.ini:/usr/share/grafana/conf/defaults.ini
      - ./grafana_data:/var/lib/grafana
    restart: always
  
# volumes:
#   prometheus_data: {}
#   grafana_data: {}