version: '3.1'

services:
  db:
    container_name: db
    image: mariadb:latest
    restart: always
    ports:
      - 3307:3306
    volumes:
      - /data/db/data:/var/lib/mysql
      - /data/db/config:/etc/mysql/conf.d
    environment:
      TZ: Asia/Seoul
      # mysql을 처음 서비스할때에 root password가 필요하다.
      # 아래의 환경변수를 포함하여 올린 후 지워준다.
      # MYSQL_ROOT_PASSWORD: ${PASSWORD}